### ISSUE TITLE
VS Code Version

### ISSUE THREAD

**Issue by ahatem** [qdbp/SalmonTheme#1]
### **First of all i want to thank you very much for this amazing theme**
I really like this theme so much. It is very comfortable for my eyes.
I am just wondering if there is any chance of having a vs code version of it or if there are any tips on how to convert it? That would be great.
### **Thank you again**

**Comment by qdbp** [comment]
I'm happy you like the theme.

Being rather busy these days, I will not be generating a plugin myself for any editor other than the Intellij ones in the forseeable future, and I am not familiar with VSCode theming.

However, this theme is generated by my open-source mini-library https://github.com/qdbp/palette_gen from yaml configuration files which are found in this repo. In order to generate a VS Code theme, you would need to extend the palette gen repo with appropriate model classes that can serve as a "front end compiler" to whatever stylesheets VS code uses.

For those interested, I am open to reviewing and accepting pull requests for a VS Code "frontend" into palette gen.
